import Head from "next/head";
import { WalletSection } from "../components";
import { chains } from "chain-registry";

import { useTheme } from "../contexts/theme";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";
import { useValidatorsQuery } from "../query/useQueries";
import { useChainName } from "../contexts/chainName";
import ChainSelector from "../components/react/chain-selector";

export default function Home() {
  const { chainName } = useChainName();
  const { theme, toggleTheme } = useTheme();
  const { validatorsData, isError, isLoading } = useValidatorsQuery(chainName);

  return (
    <div className="max-w-screen py-10 px-10 mx-6 lg:mx-auto">
      <Head>
        <title>Block Explorer</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row justify-end mb-4 gap-4 my-auto">
        <WalletSection chainName={chainName} />
        <ChainSelector chains={chains} />
        <button
          className="inline-flex items-center justify-center w-12 h-11 border rounded-lg hover:bg-black/10 dark:hover:bg-white/10 border-black/10 dark:border-white/10"
          onClick={toggleTheme}
        >
          {theme === "light" ? (
            <MoonIcon className=" text-black w-5 h-5" />
          ) : (
            <SunIcon className=" text-white  w-6 h-6" />
          )}
        </button>
      </div>
    </div>
  );
}
